# Generated by Django 6.0.5 on 2026-06-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='blog/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.blogpost')),
            ],
        ),
    ]
