# Generated by Django 6.0.5 on 2026-06-16 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
