# Generated by Django 6.0.5 on 2026-06-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='contenido',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='blog/portadas/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='resumen',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlogSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/contenido/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='core.blogpost')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogImagen',
        ),
    ]
