# Generated by Django 6.0.6 on 2026-06-18 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blogpost_contenido_blogpost_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
