# Generated by Django 6.0.6 on 2026-06-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='contenido',
        ),
    ]
