# Generated by Django 6.0.6 on 2026-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_blogpost_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
