# Generated by Django 6.0.6 on 2026-06-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='usuario', max_length=20),
        ),
    ]
