# Generated by Django 6.0.6 on 2026-07-06 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_testrespuesta_pregunta_test_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='imagen',
            field=models.ImageField(upload_to='tests/'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='resultados/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.test')),
            ],
        ),
        migrations.AlterField(
            model_name='opcion',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultado'),
        ),
        migrations.CreateModel(
            name='ResultadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultado')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
