# Generated by Django 6.0.6 on 2026-07-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_test_categoria_alter_test_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadousuario',
            options={'ordering': ['-actualizado']},
        ),
        migrations.AddField(
            model_name='resultadousuario',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_resultado', to='core.resultado'),
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_usuario', to='core.test'),
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='resultadousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'test'), name='resultado_unico_por_usuario_test'),
        ),
    ]
