# Generated by Django 6.0.6 on 2026-07-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_resultadousuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadousuario',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='resultadousuario',
            name='resultado_unico_por_usuario_test',
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultado'),
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
        migrations.AlterField(
            model_name='resultadousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_resultado_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
