# Generated by Django 6.0.6 on 2026-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_resultadousuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
