# Generated by Django 6.0.6 on 2026-07-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_precio_base_variante_precio_detal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together={('marca', 'nombre')},
        ),
    ]
