# Generated by Django 6.0.6 on 2026-07-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_coleccion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
