# Generated by Django 6.0.6 on 2026-07-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='slug',
        ),
    ]
