# Generated by Django 6.0.6 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='gmail_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respuesta_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='respuesta_cliente_leida',
            field=models.BooleanField(default=True),
        ),
    ]
