# Generated by Django 6.0.6 on 2026-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contacto_fecha_cliente_contacto_gmail_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='respuesta_cliente_leida',
            field=models.BooleanField(default=False),
        ),
    ]
