# Generated by Django 6.0.6 on 2026-07-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_contacto_respuesta_cliente_leida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
