# Generated by Django 6.0.6 on 2026-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_contacto_gmail_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
