# Generated by Django 6.0.6 on 2026-07-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notaadmin_recordatorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recordatorio',
            options={},
        ),
        migrations.RemoveField(
            model_name='notaadmin',
            name='completada',
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='texto',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
