# Generated by Django 6.0.6 on 2026-07-16 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_notaadmin_options_alter_recordatorio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaadmin',
            options={'ordering': ['completada', '-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='recordatorio',
            options={'ordering': ['fecha']},
        ),
        migrations.AddField(
            model_name='notaadmin',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
    ]
