# Generated by Django 6.0.6 on 2026-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_eventocalendario_ideacontenido_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
