# Generated by Django 6.0.6 on 2026-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='ideacontenido',
            options={'ordering': ['estado', '-creada'], 'verbose_name': 'Idea de contenido', 'verbose_name_plural': 'Ideas de contenido'},
        ),
        migrations.AlterModelOptions(
            name='notaadmin',
            options={'ordering': ['completada', '-fecha_creacion'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='recordatorio',
            options={'ordering': ['fecha'], 'verbose_name': 'Recordatorio', 'verbose_name_plural': 'Recordatorios'},
        ),
        migrations.RemoveField(
            model_name='ideacontenido',
            name='completada',
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideacontenido',
            name='actualizada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ideacontenido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('publicada', 'Publicada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ideacontenido',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaadmin',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notaadmin',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
