# Generated by Django 6.0.6 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_eventocalendario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('color', models.CharField(choices=[('rosa', 'Rosa'), ('amarillo', 'Amarillo'), ('lila', 'Lila'), ('azul', 'Azul')], default='rosa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
