# Generated by Django 6.0.6 on 2026-07-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_postit_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postits', to=settings.AUTH_USER_MODEL),
        ),
    ]
