# Generated by Django 6.0.6 on 2026-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_postit_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacontenido',
            name='categoria',
            field=models.CharField(choices=[('galeria', 'Galeria'), ('post', 'Post'), ('historia', 'Historia'), ('blog', 'Blog'), ('otro', 'Otro')], default='post', max_length=30),
        ),
    ]
