# Generated by Django 6.0.6 on 2026-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_ideacontenido_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variante',
            old_name='precio_detal',
            new_name='precio_100',
        ),
        migrations.AddField(
            model_name='variante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variante',
            name='precio_1200',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variante',
            name='precio_500',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variante',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variante',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PrecioEscalado',
        ),
    ]
