# Generated by Django 6.0.6 on 2026-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_precio_detal_variante_precio_100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['monto_minimo'],
            },
        ),
        migrations.RemoveField(
            model_name='variante',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='precio_100',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='precio_1200',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='precio_500',
        ),
    ]
