# Generated by Django 6.0.6 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_nivelprecio_remove_variante_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='codigo_tono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
