# Generated by Django 6.0.6 on 2026-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_variante_codigo_tono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='tono',
        ),
        migrations.AddField(
            model_name='variante',
            name='nombre_tono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del tono'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='codigo_tono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del tono'),
        ),
    ]
