# Generated by Django 6.0.6 on 2026-07-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_variante_tono_variante_nombre_tono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='tamano',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variante',
            name='codigo_tono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
