# Generated by Django 6.0.6 on 2026-07-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_etiqueta_producto_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
