# Generated by Django 6.0.6 on 2026-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_kit_kitproducto_kit_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='sku',
            field=models.CharField(blank=True, help_text='Código interno del kit. Si se deja vacío, se genera automáticamente.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Unidades disponibles de este kit.'),
        ),
    ]
