# Generated by Django 6.0.6 on 2026-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_kit_sku_kit_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo real del producto antes de aplicar margen de rentabilidad.', max_digits=12),
        ),
    ]
