# Generated by Django 6.0.6 on 2026-08-10 19:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_producto_costo_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='descuento_personalizado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado al precio normal del kit.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='kit',
            name='precio_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo legado. Usa descuento_personalizado para calcular el precio final.', max_digits=12, null=True),
        ),
    ]
