# Generated by Django 6.0.6 on 2026-08-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_kit_descuento_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='info_extra',
            field=models.TextField(blank=True, help_text='Información adicional del producto (composición, modo de uso, cuidados, etc.)', null=True),
        ),
    ]
