# Generated by Django 6.0.6 on 2026-08-21 18:54
# Corregido a mano: default de Pedido.creado y generación segura de Pedido.referencia

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def generar_referencias_unicas(apps, schema_editor):
    """
    Rellena 'referencia' con un valor único por fila para los Pedidos
    que ya existían antes de agregar el campo (evita choque con el
    constraint unique=True al alterar el campo más abajo).
    """
    Pedido = apps.get_model('core', 'Pedido')
    for pedido in Pedido.objects.all():
        pedido.referencia = f"PED-{pedido.pk:06d}"
        pedido.save(update_fields=['referencia'])


def noop(apps, schema_editor):
    # No hace falta revertir: si se deshace la migración, el campo se elimina igual.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_carritoitem_precio_carrito_actualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='precio',
        ),
        migrations.AddField(
            model_name='pago',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_wompi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='creado',
            # Corregido: antes tenía default=1 (entero), lo cual rompía
            # porque el campo es DateTimeField y esperaba una fecha.
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # --- referencia: se agrega primero SIN unique/blank permitido temporalmente,
        # se rellena con valores únicos por fila, y luego se aplica el constraint unique.
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(generar_referencias_unicas, noop),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto_nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='variante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]