# Generated by Django 6.0.6 on 2026-08-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_pedido_costo_envio_pedido_descuento_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='porcentaje_descuento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nivel_precio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
