# Generated by Django 6.0.6 on 2026-08-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_pedido_costo_envio_remove_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_detalle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
