# Generated by Django 6.0.6 on 2026-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_pedido_costo_envio_pedido_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_envio',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando pedido'), ('EN_PROCESO', 'En proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('FINALIZADO', 'Finalizado')], default='PREPARANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
