# Generated by Django 6.0.6 on 2026-08-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pedido_estado_envio_pedido_fecha_envio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carritoitem',
            name='carrito_variante_unica',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='core.kit'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.kit'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='core.variante'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.variante'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variante__isnull', False)), fields=('carrito', 'variante'), name='carrito_variante_unica'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('kit__isnull', False)), fields=('carrito', 'kit'), name='carrito_kit_unica'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kit__isnull', True), ('variante__isnull', False)), models.Q(('kit__isnull', False), ('variante__isnull', True)), _connector='OR'), name='carrito_item_variante_xor_kit'),
        ),
    ]
