# Generated by Django 6.0.6 on 2026-08-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_carritoitem_carrito_variante_unica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItemKitSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_kit', to='core.carritoitem')),
                ('kit_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_carrito', to='core.kitproducto')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variante')),
            ],
            options={
                'unique_together': {('carrito_item', 'kit_producto')},
            },
        ),
    ]
