# Generated by Django 6.0.6 on 2026-08-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_carritoitemkitseleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItemKitSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('variante_nombre', models.CharField(max_length=255)),
                ('kit_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kitproducto')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_kit', to='core.pedidoitem')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variante')),
            ],
        ),
    ]
