# Generated by Django 6.0.6 on 2026-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_pedidoitemkitseleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionEmprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('presupuesto_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto_interes', models.CharField(choices=[('gloss', 'Gloss'), ('skincare', 'Skincare'), ('pestanas', 'Pestañas'), ('kits', 'Kits beauty')], max_length=30)),
                ('plataforma', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=30)),
                ('inversion_estimada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancia_estimada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recomendacion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('kits', models.ManyToManyField(blank=True, related_name='recomendaciones_emprendimiento', to='core.kit')),
                ('productos', models.ManyToManyField(blank=True, related_name='recomendaciones_emprendimiento', to='core.producto')),
            ],
        ),
    ]
