# Generated by Django 6.0.6 on 2026-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_recomendacionemprendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='inversion_maxima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inversión máxima recomendada para este kit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='kit',
            name='inversion_minima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inversión mínima recomendada para este kit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='kit',
            name='nivel_recomendado',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='', help_text='Nivel de emprendedor para el que se recomienda este kit.', max_length=20),
        ),
        migrations.AddField(
            model_name='kit',
            name='plataforma_recomendada',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('todas', 'Todas')], default='', help_text='Plataforma donde se recomienda vender este kit.', max_length=20),
        ),
        migrations.AddField(
            model_name='kit',
            name='recomendacion_texto',
            field=models.TextField(blank=True, default='', help_text='Mensaje que verá el usuario cuando este kit sea recomendado por el test.'),
        ),
        migrations.AddField(
            model_name='kit',
            name='recomendar_test',
            field=models.BooleanField(default=False, help_text='Si está activo, este kit podrá aparecer en las recomendaciones del test de emprendimiento.'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tipo_negocio',
            field=models.CharField(blank=True, default='', help_text='Tipo de negocio o productos. Ej: Gloss, Skincare, Pestañas, Kits beauty.', max_length=100),
        ),
    ]
