# Generated by Django 6.0.6 on 2026-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_kit_inversion_maxima_kit_inversion_minima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='producto_interes',
            field=models.CharField(choices=[('gloss', 'Gloss'), ('skincare', 'Skincare'), ('pestanas', 'Pestañas'), ('kits', 'Kits beauty'), ('maquillaje', 'Maquillaje'), ('accesorios', 'Accesorios')], max_length=30),
        ),
    ]
