# Generated by Django 6.0.6 on 2026-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_recomendacionemprendimiento_producto_interes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomendacionemprendimiento',
            options={'ordering': ['presupuesto_min', '-fecha_creacion'], 'verbose_name': 'Recomendación de emprendimiento', 'verbose_name_plural': 'Recomendaciones de emprendimiento'},
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='ganancia_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='inversion_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='producto_interes',
            field=models.CharField(blank=True, choices=[('gloss', 'Gloss'), ('skincare', 'Skincare'), ('pestanas', 'Pestañas'), ('kits', 'Kits beauty'), ('maquillaje', 'Maquillaje'), ('accesorios', 'Accesorios')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='recomendacion',
            field=models.TextField(blank=True),
        ),
    ]
