# Generated by Django 6.0.6 on 2026-08-30 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_recomendacionemprendimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEmprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recomendacion', models.CharField(blank=True, default='', max_length=200)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.CharField(blank=True, default='', max_length=30)),
                ('plataforma', models.CharField(blank=True, default='', max_length=30)),
                ('ganancia_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('datos', models.JSONField(help_text='Respuesta completa de /api/recomendar-emprendimiento/ en el momento de guardar.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_emprendimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de emprendimiento',
                'verbose_name_plural': 'Reportes de emprendimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
