# Generated by Django 6.0.6 on 2026-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_reporteemprendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacionemprendimiento',
            name='producto_interes',
            field=models.CharField(blank=True, choices=[('accesorios', 'Accesorios'), ('skincare', 'Skincare'), ('facial', 'Facial'), ('ojos', 'Ojos'), ('general', 'General'), ('kits', 'Kits')], max_length=30, null=True),
        ),
    ]
