# Generated by Django 6.0.6 on 2026-09-02 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_proveedor_delete_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='encargado',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre del encargado solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 10 números.', regex='^[0-9]{7,10}$')]),
        ),
    ]
